### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by averagehat** [DCGenomics/seqr#14]
Including a `.travis.yml` file isn't difficult and might help guarantee (and document) working install, i.e. #11

**Comment by averagehat** [comment]
This is set up but in the repo but currently pointing to my fork; I don't have admin privileges to add it to travis.
@DCGenomics [could you do that for me?](http://docs.travis-ci.com/user/getting-started/)

**Comment by lianyi** [comment]
I'll follow up on this ticket.

**Comment by averagehat** [comment]
Closed, see #26
