### ISSUE TITLE
index command

### ISSUE THREAD

**Issue by lianyi** [DCGenomics/seqr#29]
Not sure if i was looking at the right place.

**seqr/src/main/java/gov/nih/nlm/ncbi/seqr/solr/SeqrController.java**

```
   public SolrDocumentList index(String proteinSequence) {
        return null;
    }
```

Was this index method overridden/implemented somewhere that able to index the JSON and/or FASTA files?  I saw samples in unit testing that we able to index josn files though.

**Comment by averagehat** [comment]
We didn't finish this at the hackathon. I am working on adding the functionality in, it's very simple. Probably I should have had it raise an error but I didn't think of that at the time.

**Comment by averagehat** [comment]
I am planning to just add a solrInputDocument like so:

``` python
{ "sequence" : "ACGT..."
"defline" : ">gi|foo|bar"...
}
```

**Comment by lianyi** [comment]
Got it, thanks @averagehat ! 

Also here is a list of fields that pre-defined at this moment: Where **id** is a required **int** field. 

``` json
{
    "id": 20140829,
    "nrgi": "15676503",
    "acxn": "Q9K0J8",
    "pig": 129513,
    "taxid": "122586",
    "blastname": "b-proteobacteria",
    "sciname": "Neisseria meningitidis MC58",
    "lineage": "/root/cellular organisms/Bacteria/Proteobacteria/Betaproteobacteria/Neisseriales/Neisseriaceae/Neisseria/Neisseria meningitidis/Neisseria meningitidis serogroup B/Neisseria meningitidis MC58",
    "preftaxid": "64",
    "prefaxname": "Betaproteobacteria",
    "origdefline": "RecName: Full=Maf-like protein NMB0598 [Neisseria meningitidis MC58]",
    "defline": "RecName: Full=Maf-like protein NMB0598 ",
    "seqlen": "202",
    "sequence": "MNTLYLGSNSPRRMEILTQLGYRVIQLPAGIDESVKAGETPFAYVQRMAEEKNRTALTLFCETNGTMPDFPLITADTC"
}
```

**Comment by averagehat** [comment]
where does the "id" field come from?

**Comment by lewisg-ncbi** [comment]
Mike,

It's the standard ncbi integer identifier for a sequence, normally called a gi.

Best,
Lewis

**Comment by lianyi** [comment]
code merged
