### ISSUE TITLE
How-to for starting solr server

### ISSUE THREAD

**Issue by averagehat** [DCGenomics/seqr#30]
It would be good to have directions on how to use solr server. I have tried downloading solr from here http://www.apache.org/dyn/closer.lua/lucene/solr/5.3.0  

``` bash
bash-4.1$ echo $SOLR_HOME 
/home/AMED/michael.panciera/projects/seqr/testdata/solr
```

`solr-5.3.0/bin/solr start -s $SOLR_HOME` works, but

```
bash-4.1$    curl "localhost:8983/solr/sequence/select?q=*:*"
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 404 </title>
</head>
<body>
<h2>HTTP ERROR: 404</h2>
<p>Problem accessing /solr/sequence/select. Reason:
<pre>    Not Found</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>
```

I wonder if this doesn't have to do with the extra libs we require?

**Comment by averagehat** [comment]
https://paste.fedoraproject.org/262715/14412206/

**Comment by lianyi** [comment]
Right, currently the blessed solr version is 4.10.4. 

This Readme might help:  https://github.com/NCBI-Hackathons/seqr/blob/master/testdata/solr/README.md

 if the issue persist after switching to 4.10.4, another possibility is the heap requirement.  it might be nice to know if the following works, which give the solr 4G heap mem:

```
$SOLR_BIN/solr start -m 4G -s $SOLR_HOME
```

**Comment by averagehat** [comment]
I created a makefile for solr and seqr (maven): PR #31
 added a wiki page: https://github.com/NCBI-Hackathons/seqr/wiki/Using-Solr-Server

I want to add in the manual commands (calling solr without the makefile) as well.

**Comment by lianyi** [comment]
Cool, I only made a minor change in #33,  It's working from what I just tested on CentOS 6.
